# fine-tune text, vision or both
# "text"
# "vision"
# "hybrid"
# also used for fine tuned metric
mode: "hybrid"

save_folders:
  text_folder: "./Output/beans_text_WB"
  vision_folder: "./Output/beans_vision_WB"
  text_vision_folder: "./Output/beans_text_vision_WB"

training_args:
  eval_strategy: "epoch"
  per_device_train_batch_size: 64
  per_device_eval_batch_size: 64
  optim: "adamw_torch"
  lr: 0.001
  epochs: 25
  save_strategy: "best"
  seed: 104
  metric_for_best_model: "eval_loss"
  label_names: ["labels"]
  dataloader_pin_memory: true
  tf32: true #false for older than Ampere NVIDIA Architecture GPU 

lora_args:
  r: 16
  alpha: 32
  dropout: 0.1
  task_type: "FEATURE_EXTRACTION"